version: "3"
services:
  dnsmasq:
    image: quay.io/coreos/dnsmasq
    container_name: "dnsmasq"
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq.resolv.conf:/etc/dnsmasq.resolv.conf
      - ./resolv.conf:/etc/resolv.conf
      - ./my-hosts:/etc/my-hosts
    entrypoint:
      - /usr/sbin/dnsmasq
      - -d
      - -q
